name: Daily News

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install typescript and types
        run: npm install -g typescript && npm install --save-dev @types/node

      - name: Compile TypeScript
        run: tsc

      - name: Build
        run: node dist_ts/build.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload to COS
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.COS_SECRET_ID }}
          secret_key: ${{ secrets.COS_SECRET_KEY }}
          cos_bucket: dailynews-1419760006
          cos_region: ap-shanghai
          local_path: dist
          remote_path: /
          clean: true
